steps:
  - name: gcr.io/kaniko-project/executor:latest
    id: v1-back-build
    waitFor: ['-']
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/bookish-pancake/v1/backgrpc:latest
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/bookish-pancake/v1/backgrpc:$COMMIT_SHA
      - --dockerfile=v1/backgrpc/Dockerfile

  - name: gcr.io/kaniko-project/executor:latest
    id: v1-front-build
    waitFor: ['-']
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/bookish-pancake/v1/frontweb:latest
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/bookish-pancake/v1/frontweb:$COMMIT_SHA
      - --dockerfile=v1/frontweb/Dockerfile

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: v1-back-deploy
    waitFor: ['v1-back-build']
    entrypoint: gcloud
    args:
      - run
      - deploy
      - v1-backgrpc
      - --image
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/bookish-pancake/v1/backgrpc:$COMMIT_SHA
      - --region
      - asia-northeast1

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: v1-front-deploy
    waitFor: ['v1-front-build']
    entrypoint: gcloud
    args:
      - run
      - deploy
      - v1-frontweb
      - --image
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/bookish-pancake/v1/frontweb:$COMMIT_SHA
      - --region
      - asia-northeast1

  - name: gcr.io/kaniko-project/executor:latest
    id: v2-back-build
    waitFor: ['-']
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/bookish-pancake/v2/backgrpc:latest
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/bookish-pancake/v2/backgrpc:$COMMIT_SHA
      - --dockerfile=v2/backgrpc/Dockerfile

  - name: gcr.io/kaniko-project/executor:latest
    id: v2-front-build
    waitFor: ['-']
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/bookish-pancake/v2/frontweb:latest
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/bookish-pancake/v2/frontweb:$COMMIT_SHA
      - --dockerfile=v2/frontweb/Dockerfile

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: v2-back-deploy
    waitFor: ['v2-back-build']
    entrypoint: gcloud
    args:
      - run
      - deploy
      - v2-backgrpc
      - --image
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/bookish-pancake/v2/backgrpc:$COMMIT_SHA
      - --region
      - asia-northeast1

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: v2-front-deploy
    waitFor: ['v2-front-build']
    entrypoint: gcloud
    args:
      - run
      - deploy
      - v2-frontweb
      - --image
      - asia-northeast1-docker.pkg.dev/$PROJECT_ID/bookish-pancake/v2/frontweb:$COMMIT_SHA
      - --region
      - asia-northeast1
